#!/usr/bin/env bash
# publish.sh — atomic release publish to the dist host (spec 093/US033).
#
# Clients must never observe a half-uploaded release (tarball present but
# checksums/version.json missing). The protocol:
#   1. upload the full artifact set into releases/<version>  (inert dir)
#   2. verify remote consistency (sha256 of the uploaded tarball)
#   3. swap the `current` symlink atomically (ln -sfn + mv -T)
#   4. update top-level version.json LAST — it is the pointer clients poll;
#      until it changes, nobody looks at the new directory.
# The previous release directory is retained for instant repoint.
#
# Usage: PUBLISH_HOST=user@host ./scripts/publish.sh <version>
#   PUBLISH_STAGING=1 targets staging/releases/<ver> instead — the release
#   stays invisible to clients until scripts/promote.sh verifies + swaps it.
#   (dry-run: PUBLISH_HOST= ./scripts/publish.sh <version> ./staged-dist)

set -euo pipefail
cd "$(dirname "$0")/.." || exit 1

# spec 093/US059: --dry-run prints the plan and exits before any change;
# --local <root> publishes into a local docroot instead of ssh.
DRY="${DRY_RUN:-0}"
LOCAL_ROOT=""
VERSION=""
DIST_DIR="dist"
while [ $# -gt 0 ]; do
    case "$1" in
        --dry-run) DRY=1; shift ;;
        --local)   LOCAL_ROOT="$2"; shift 2 ;;
        -*)        echo "publish: unknown flag $1" >&2; exit 2 ;;
        *)         [ -z "$VERSION" ] && VERSION="$1" || DIST_DIR="$1"; shift ;;
    esac
done
# dry-run without a version defaults to the metadata's current version —
# the plan for "what a publish right now would do" is the common case.
if [ -z "$VERSION" ]; then
    VERSION=$(python3 -c 'import json;print(json.load(open("version.json"))["version"])' 2>/dev/null || true)
fi
VERSION="${VERSION:?usage: publish.sh [--dry-run] [--local root] <version> [dist-dir]}"
HOST="${PUBLISH_HOST:-}"
ROOT="${PUBLISH_ROOT:-/var/www/proxmoxvex-dist}"

plan() { echo "[dry-run] $*"; }

die() { echo "publish: FAIL: $*" >&2; exit 1; }

# cdn_purge: invalidate CDN edge caches for metadata + the -latest pointer.
# Best-effort: a failed purge warns but never blocks the release — edges
# revalidate within the short TTL anyway (see deploy/nginx.conf).
cdn_purge() {
    local api="${CDN_API:-}" token="${CDN_TOKEN:-}"
    if [ -z "$api" ] || [ -z "$token" ]; then
        echo "publish: WARN: CDN_API/CDN_TOKEN unset — skipping edge purge" >&2
        return 0
    fi
    curl -fsS -X POST "$api" \
        -H "Authorization: Bearer $token" \
        -H "Content-Type: application/json" \
        -d '{"files":[
              "/version.json",
              "/version.json.asc",
              "/checksums.txt",
              "/transparency.log",
              "/transparency.log.asc",
              "/downloads/ProxmoxVEx-latest.tar.gz",
              "/downloads/ProxmoxVEx-latest.tar.gz.asc"
            ]}' \
        || { echo "publish: WARN: CDN purge failed; edges may lag up to their TTL" >&2; return 0; }
    echo "publish: CDN purge issued for metadata + latest pointer"
    return 0
}

# write_latest_conf <dir> <version>: generate the nginx include that 302s
# /downloads/ProxmoxVEx-latest.tar.gz to the versioned artifact. Written via
# tmp+mv so nginx never reads a half-written file (spec 093/US038).
write_latest_conf() {
    local dir="$1" ver="$2"
    mkdir -p "$dir"
    cat > "$dir/latest.conf.tmp" <<EOF
# GENERATED by scripts/publish.sh — do not edit by hand.
# -latest is a pointer, not a file: clients get a redirect to the immutable
# versioned artifact, so a mid-publish state can never serve torn bytes.
location = /downloads/ProxmoxVEx-latest.tar.gz {
    add_header Cache-Control "public, max-age=60" always;
    return 302 /downloads/ProxmoxVEx-${ver}.tar.gz;
    }
location = /downloads/ProxmoxVEx-latest.tar.gz.asc {
    add_header Cache-Control "public, max-age=60" always;
    return 302 /downloads/ProxmoxVEx-${ver}.tar.gz.asc;
    }
EOF
    mv -T "$dir/latest.conf.tmp" "$dir/latest.conf"
}

# publish_swap <docroot> <version>: atomically repoint `current`. Exported
# for tests; in production runs over ssh on the host.
publish_swap() {
    local root="$1" ver="$2"
    [ -d "$root/releases/$ver" ] || { echo "no staged release: $root/releases/$ver" >&2; return 1; }
    # ln -sfn into a temp name then mv -T: the rename is atomic on POSIX, so
    # readers never see a missing or half-linked `current`.
    ln -sfn "releases/$ver" "$root/current.tmp"
    mv -T "$root/current.tmp" "$root/current"
}

main() {
    [ -d "$DIST_DIR" ] || die "dist dir not found: $DIST_DIR"
    local tarball="$DIST_DIR/ProxmoxVEx-${VERSION}.tar.gz"
    [ -f "$tarball" ] || die "no artifact for $VERSION in $DIST_DIR"
    local want
    want=$(sha256sum "$tarball" | awk '{print $1}')

    local sub="releases"
    [ "${PUBLISH_STAGING:-0}" = "1" ] && sub="staging/releases"

    # US059: --dry-run enumerates every planned mutation, then exits —
    # operators review the blast radius before the first byte moves.
    if [ "$DRY" = "1" ]; then
        local dest="${LOCAL_ROOT:-$HOST:$ROOT}"
        for f in "$DIST_DIR"/*; do
            plan "upload $f -> $dest/$sub/$VERSION/"
        done
        for f in version.json version.json.asc transparency.log \
                 transparency.log.asc pubkey.asc; do
            [ -f "$f" ] && plan "upload $f -> $dest/$sub/$VERSION/"
        done
        plan "verify sha256 of remote tarball == $want"
        if [ "$sub" != "staging/releases" ]; then
            plan "swap current -> releases/$VERSION (atomic mv -T)"
            plan "write+upload latest.conf redirect -> ProxmoxVEx-${VERSION}.tar.gz"
            plan "publish version.json + version.json.asc (live pointer)"
            plan "CDN purge metadata + latest pointer"
        else
            plan "stop at staging — promote.sh owns the swap"
        fi
        echo "dry-run complete"
        return 0
    fi

    # US059: --local publishes into a docroot dir instead of ssh/rsync —
    # same staged layout, same atomic swap, no network.
    if [ -n "$LOCAL_ROOT" ]; then
        mkdir -p "$LOCAL_ROOT/$sub/$VERSION"
        cp -a "$DIST_DIR/." "$LOCAL_ROOT/$sub/$VERSION/"
        for f in version.json version.json.asc transparency.log \
                 transparency.log.asc pubkey.asc; do
            [ -f "$f" ] && cp "$f" "$LOCAL_ROOT/$sub/$VERSION/"
        done
        if [ "$sub" = "staging/releases" ]; then
            echo "publish: staged at $LOCAL_ROOT/$sub/$VERSION"
            return 0
        fi
        publish_swap "$LOCAL_ROOT" "$VERSION"
        write_latest_conf "$LOCAL_ROOT" "$VERSION" 2>/dev/null || true
        echo "publish: $VERSION live under $LOCAL_ROOT"
        return 0
    fi

    if [ -z "$HOST" ]; then
        echo "publish: DRY-RUN — would upload $DIST_DIR as releases/$VERSION"
        echo "publish: tarball sha256: $want"
        return 0
    fi

    # 1) stage everything under a versioned dir (nothing public yet).
    # PUBLISH_STAGING=1 lands it in staging/releases/ for the promote gate.
    local sub="releases"
    [ "${PUBLISH_STAGING:-0}" = "1" ] && sub="staging/releases"
    ssh "$HOST" "mkdir -p '$ROOT/$sub/$VERSION'"
    rsync -a --delete "$DIST_DIR/" "$HOST:$ROOT/$sub/$VERSION/"
    # metadata + signatures go in the same staged set
    for f in version.json version.json.asc transparency.log transparency.log.asc \
             pubkey.asc; do
        [ -f "$f" ] && scp -q "$f" "$HOST:$ROOT/$sub/$VERSION/"
    done

    # 2) verify what actually landed — compare remote sha256 to local
    local got
    got=$(ssh "$HOST" "sha256sum '$ROOT/$sub/$VERSION/ProxmoxVEx-${VERSION}.tar.gz' | awk '{print \$1}'")
    [ "$got" = "$want" ] || die "remote checksum mismatch: $got != $want"

    # staging stops here — promote.sh owns the swap after its own e2e verify
    if [ "$sub" = "staging/releases" ]; then
        echo "publish: staged at $HOST:$ROOT/$sub/$VERSION — run scripts/promote.sh $VERSION to go live"
        return 0
    fi

    # 3) atomic swap on the host (remote runs publish_swap's equivalent)
    ssh "$HOST" "ln -sfn 'releases/$VERSION' '$ROOT/current.tmp' && mv -T '$ROOT/current.tmp' '$ROOT/current'"
    echo "publish: $HOST current -> releases/$VERSION (previous release retained)"

    # 4) US038: regenerate the -latest redirect include and ship it
    # atomically (tmp upload + mv -T on the host).
    write_latest_conf deploy "$VERSION"
    scp -q deploy/latest.conf "$HOST:$ROOT/latest.conf.tmp"
    ssh "$HOST" "mv -T '$ROOT/latest.conf.tmp' '$ROOT/latest.conf'"
    echo "publish: latest.conf -> ProxmoxVEx-${VERSION}.tar.gz"

    # 5) LAST: publish the new pointer metadata where clients poll it
    scp -q version.json version.json.asc "$HOST:$ROOT/"
    echo "publish: version.json updated — release $VERSION live"

    # 6) US036: purge CDN edges for the paths that just changed
    cdn_purge
}

main "$@"
