# --- ProxmoxVEx auto-header start ---
# --------------------------------------------------------------------
# File:        ProxmoxVEx/models/permissions.py
# Project:     ProxmoxVEx
# Version:     1.2.303
# Build:       2026.09.04
# Description: ProxmoxVEx Permissions & Roles - Layer 0
# Docs:        https://proxmoxvex.local/docs
# Generated:   2026-09-04
# --------------------------------------------------------------------
# --- ProxmoxVEx auto-header end ---
"""
ProxmoxVEx Permissions & Roles - Layer 0
No ProxmoxVEx imports allowed.
"""

# User roles
ROLE_ADMIN = "admin"
ROLE_USER = "user"
ROLE_VIEWER = "viewer"

# Builtin roles - cannot be deleted
BUILTIN_ROLES = [ROLE_ADMIN, ROLE_USER, ROLE_VIEWER]

PERMISSIONS = {
    # vm stuff
    "vm.view": "View VMs and containers",
    "vm.start": "Start VMs and containers",
    "vm.stop": "Stop VMs and containers",
    "vm.restart": "Restart VMs and containers",
    "vm.console": "Access VM console",
    "vm.migrate": "Migrate VMs between nodes",
    "vm.clone": "Clone VMs",
    "vm.delete": "Delete VMs and containers",
    "vm.create": "Create new VMs and containers",
    "vm.config": "Modify VM configuration",
    "vm.snapshot": "Create/delete snapshots",
    "vm.backup": "Backup VMs",
    "vm.template": "Convert to/from template",
    # Converter permissions
    "converter.view": "View conversion/resize jobs and presets",
    "converter.run": "Run conversion/resize jobs",
    "converter.admin": "Manage converter presets, hooks, and cancel any job",
    # Cluster permissions
    "cluster.view": "View cluster info",
    "cluster.add": "Add new clusters",
    "cluster.delete": "Remove clusters",
    "cluster.config": "Modify cluster settings",
    "cluster.join": "Join nodes to cluster",
    "cluster.admin": "Full cluster administration (join/remove nodes)",
    # Node permissions
    "node.view": "View node status",
    "node.shell": "Access node shell",
    "node.maintenance": "Toggle maintenance mode",
    "node.update": "Update node packages",
    "node.reboot": "Reboot nodes",
    "node.network": "Modify network config",
    "node.config": "Change node options",
    "node.certificate": "Manage SSL certificates",
    "node.power": "Shutdown/wake nodes",
    # Storage permissions
    "storage.view": "View storage",
    "storage.upload": "Upload files to storage",
    "storage.delete": "Delete files from storage",
    "storage.config": "Modify storage config",
    "storage.create": "Add new storage",
    "storage.download": "Download ISOs/templates",
    # Backup permissions
    "backup.view": "View backups",
    "backup.create": "Create backups",
    "backup.restore": "Restore from backup",
    "backup.delete": "Delete backups",
    "backup.schedule": "Manage backup schedules",
    "backup.config": "Configure backup storage",
    # HA permissions
    "ha.view": "View HA status",
    "ha.config": "Configure HA settings",
    "ha.groups": "Manage HA groups",
    "ha.resources": "Add/remove HA resources",
    # Firewall permissions
    "firewall.view": "View firewall rules",
    "firewall.edit": "Modify firewall rules",
    "firewall.aliases": "Manage aliases/IPsets",
    # Pool/Resource permissions
    "pool.view": "View resource pools",
    "pool.manage": "Create/delete pools",
    "pool.assign": "Assign VMs to pools",
    # Replication
    "replication.view": "View replication jobs",
    "replication.manage": "Create/delete replication",
    # Ceph
    "ceph.manage": "Manage Ceph OSD, pools, monitors, MDS",
    # SDN
    "sdn.manage": "Manage SDN zones, vnets, subnets, controllers",
    # Alerts
    "alert.manage": "Create, edit, delete alert rules",
    # IDS/IPS permissions
    "ids.view": "View IDS/IPS alerts, rules, and reports",
    "ids.rules": "Create, edit, and delete IDS/IPS detection rules",
    "ids.policies": "Create, edit, and delete IDS/IPS response policies",
    "ids.admin": "Manage IDS/IPS configuration and monitored segments",
    # Site Recovery - Mar 2026
    "site_recovery.view": "View recovery plans and events",
    "site_recovery.manage": "Create/edit/delete recovery plans and VMs",
    "site_recovery.failover": "Execute failover, failback and test operations",
    # Terraform / IaC permissions
    "terraform.view": "View Terraform exports",
    "terraform.export": "Export cluster state to Terraform HCL",
    # Ansible / IaC permissions
    "ansible.view": "View Ansible exports",
    "ansible.export": "Export cluster state to Ansible playbooks",
    # Packer / IaC permissions
    "packer.view": "View Packer sync status",
    "packer.sync": "Sync Packer templates and images",
    "packer.import": "Import Packer templates and images",
    "packer.library": "View Packer template library",
    "packer.widget": "View Packer dashboard widget",
    "packer.alerts": "Manage Packer alert channel",
    "packer.policy": "Manage Packer policy adapter",
    "packer.roles": "Manage Packer role mapping",
    "packer.workflow": "Manage Packer automation workflow",
    # Kubernetes / integrations permissions
    "kubernetes.export": "Export cluster state to Kubernetes manifests",
    "kubernetes.connector": "Manage Kubernetes connector configuration",
    "kubernetes.sync": "Sync cluster state to Kubernetes",
    "kubernetes.import": "Import Kubernetes manifests into the cluster",
    "kubernetes.library": "View Kubernetes template library",
    "kubernetes.widget": "View Kubernetes dashboard widget",
    "kubernetes.alerts": "Manage Kubernetes alert channel",
    "kubernetes.policy": "Manage Kubernetes policy adapter",
    "kubernetes.roles": "Manage Kubernetes role mapping",
    "kubernetes.workflow": "Manage Kubernetes automation workflow",
    # Docker / integrations permissions
    "docker.export": "Export cluster state to Docker assets",
    "docker.connector": "Manage Docker connector configuration",
    # Plugin permissions
    "plugins.view": "View installed plugins",
    "plugins.manage": "Enable, disable and configure plugins",
    # LDAP permissions
    "ldap.export": "Export cluster state to LDAP assets",
    "ldap.connector": "Manage LDAP connector configuration",
    "ldap.sync": "Sync users from LDAP",
    "ldap.import": "Import users from LDAP",
    "ldap.templates": "Manage LDAP templates",
    "ldap.widget": "View LDAP dashboard widget",
    "ldap.alert": "Manage LDAP alert channel",
    "ldap.policy": "Manage LDAP policy adapter",
    "ldap.role_mapping": "Manage LDAP role mapping",
    "ldap.workflow": "Manage LDAP automation workflows",
    # Active Directory permissions
    "active_directory.export": "Export cluster state to Active Directory assets",
    "active_directory.connector": "Manage Active Directory connector configuration",
    "active_directory.sync": "Sync users from Active Directory",
    "active_directory.import": "Import users from Active Directory",
    "active_directory.templates": "Manage Active Directory templates",
    "active_directory.widget": "View Active Directory dashboard widget",
    "active_directory.alert": "Manage Active Directory alert channel",
    "active_directory.policy": "Manage Active Directory policy adapter",
    "active_directory.role_mapping": "Manage Active Directory role mapping",
    "active_directory.workflow": "Manage Active Directory automation workflows",
    "vault.export": "Export cluster state to Vault",
    "vault.connector": "Manage Vault connector configuration",
    # Admin permissions
    "admin.users": "Manage users",
    "admin.roles": "Manage custom roles",
    "admin.tenants": "Manage tenants",
    "admin.groups": "Manage cluster groups",
    "admin.settings": "Modify system settings",
    "admin.scripts": "Manage and execute custom scripts",
    "admin.audit": "View audit logs",
    "admin.api": "Manage API tokens",
    # Security permissions (2026-06-10: RBAC-ification of admin-only endpoints)
    "security.lockout.view": "View IP / user brute-force lockouts",
    "security.lockout.manage": "Clear IP / user lockouts and reset password expiry",
    "security.settings.manage": "Edit security settings (IP whitelist, CORS, key rotation, compliance)",
    "update.manage": "Run and configure the in-app updater",
    # PBS permissions
    "pbs.view": "View PBS servers and datastores",
    "pbs.config": "Modify PBS server settings",
    "pbs.datastore.view": "View datastore details and snapshots",
    "pbs.datastore.create": "Create new datastores on PBS",
    "pbs.datastore.modify": "Modify datastore configuration",
    "pbs.datastore.delete": "Delete datastores from PBS",
    "pbs.datastore.gc": "Run garbage collection on datastores",
    "pbs.datastore.verify": "Run verification on datastores",
    "pbs.datastore.prune": "Prune snapshots from datastores",
    "pbs.snapshot.delete": "Delete individual snapshots",
    "pbs.snapshot.protect": "Toggle snapshot protection",
    "pbs.snapshot.notes": "Edit snapshot/group notes",
    "pbs.snapshot.browse": "Browse and download snapshot files",
    "pbs.jobs.view": "View sync/verify/prune jobs",
    "pbs.jobs.run": "Manually trigger jobs",
    "pbs.tasks.view": "View PBS tasks",
    "pbs.tasks.stop": "Stop running PBS tasks",
    "pbs.jobs.create": "Create sync/verify/prune jobs",
    "pbs.jobs.modify": "Modify existing jobs",
    "pbs.jobs.delete": "Delete jobs",
    "pbs.notifications.view": "View notification config",
    "pbs.notifications.manage": "Create/modify/delete notifications",
    "pbs.traffic.view": "View traffic control config",
    "pbs.traffic.manage": "Create/modify/delete traffic controls",
    "pbs.disks.view": "View disk information",
    "pbs.disks.smart": "View disk SMART data",
    "pbs.subscription.view": "View subscription status",
    "pbs.subscription.set": "Set subscription key",
    # VMware/vCenter permissions
    "vmware.view": "View vCenter/ESXi servers",
    "vmware.config": "Add/edit/remove vCenter connections",
    "vmware.vm.view": "View VMware VMs and details",
    "vmware.vm.power": "Start/stop/restart VMware VMs",
    "vmware.vm.snapshot": "Create/delete VMware VM snapshots",
    "vmware.vm.migrate": "Migrate VMs to Proxmox (V2V)",
    "vmware.host.view": "View ESXi host details",
    "vmware.datastore.view": "View VMware datastores",
    "vmware.network.view": "View VMware networks",
    "vmware.vm.manage": "Modify VMware VM configuration",
    "vmware.cluster.manage": "Manage VMware cluster settings (DRS, HA)",
    "vmware.export": "Export cluster state to VMware assets",
    "vmware.connector": "Manage VMware connector configuration",
    "vmware.sync": "Sync VMware state with Proxmox cluster",
    "vmware.import": "Import VMware assets into Proxmox cluster",
    "vmware.templates": "Manage VMware template library",
    "vmware.dashboard": "View VMware dashboard widget",
    "vmware.alerts": "Manage VMware alert channel",
    "vmware.policy": "Manage VMware policy adapter",
    "vmware.roles": "Manage VMware role mapping",
    "vmware.workflow": "Manage VMware automation workflow",
}

# Default permissions per role
ROLE_PERMISSIONS = {
    ROLE_ADMIN: list(PERMISSIONS.keys()),
    ROLE_USER: [
        "vm.view",
        "vm.start",
        "vm.stop",
        "vm.restart",
        "vm.console",
        "vm.migrate",
        "vm.clone",
        "vm.config",
        "vm.snapshot",
        "vm.backup",
        "converter.view",
        "converter.run",
        "cluster.view",
        "node.view",
        "storage.view",
        "storage.upload",
        "storage.download",
        "backup.view",
        "backup.create",
        "backup.restore",
        "backup.delete",
        "ha.view",
        "firewall.view",
        "pool.view",
        "pool.assign",
        "replication.view",
        "site_recovery.view",
        "plugins.view",
        "pbs.view",
        "pbs.datastore.view",
        "pbs.datastore.gc",
        "pbs.datastore.verify",
        "pbs.snapshot.notes",
        "pbs.snapshot.browse",
        "pbs.jobs.view",
        "pbs.tasks.view",
        "pbs.notifications.view",
        "pbs.traffic.view",
        "pbs.disks.view",
        "pbs.subscription.view",
        "vmware.view",
        "vmware.vm.view",
        "vmware.vm.power",
        "vmware.vm.snapshot",
        "vmware.vm.migrate",
        "vmware.vm.manage",
        "vmware.host.view",
        "vmware.datastore.view",
        "vmware.network.view",
    ],
    ROLE_VIEWER: [
        "vm.view",
        "vm.console",
        "converter.view",
        "cluster.view",
        "node.view",
        "storage.view",
        "backup.view",
        "ha.view",
        "firewall.view",
        "pool.view",
        "replication.view",
        "site_recovery.view",
        "plugins.view",
        "pbs.view",
        "pbs.datastore.view",
        "pbs.jobs.view",
        "pbs.tasks.view",
        "pbs.notifications.view",
        "pbs.traffic.view",
        "pbs.disks.view",
        "pbs.subscription.view",
        "vmware.view",
        "vmware.vm.view",
        "vmware.host.view",
        "vmware.datastore.view",
        "vmware.network.view",
    ],
}
